spring:
  application:
    name: eureka-service-invoker

eureka:
  instance:
    hostname: eureka-service-provider
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


eureka-service-provider:

  ribbon:

    listOfServers: http://localhost:9000,http://localhost:9001 # 为消费者提供服务列表

    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule


server:
  port: 9002
  servlet:
    context-path: /invoker